# https://docs.astral.sh/ruff/configuration

exclude = [
    ".git",
    "__pycache__",
    "mypy_cache",
    "pytest_cache",
    ".ruff_cache",
    ".vscode",
    ".idea",
    "alembic_migration_scripts",
    "node_modules",
    "site-packages",
]

line-length = 120
indent-width = 4
target-version = "py311"

[lint]
ignore = [
    "B006",
    "B007",
    "B009",
    "B011",
    "B012",
    "B020",
    "B027",
    "B905",
    "C901",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    "D200",
    "D201",
    "D202",
    "D205",
    "D209",
    "D212",
    "D301",
    "D400",
    "D401",
    "D404",
    "D407",
    "D415",
    "D417",
    "E501",
    "PIE796",
    "PIE804",
    "PIE810",
    "PT001",
    "PT004",
    "PT006",
    "PT007",
    "PT012",
    "PT015",
    "PT017",
    "PT018",
    "S101",
    "S102",
    "S104",
    "S105",
    "S110",
    "S311",
    "S324",
    "S608",
    "T201",
    "D213",
    "D203",
    "D413",
    "E266",
]


select = ["B", "C", "D", "E", "EXE", "F", "I", "PIE", "PT", "S", "T", "W"]

# Enable the isort rules.
extend-select = ["I"]

# Preview mode enables a collection of newer lint rules, fixes, and formatter style changes that are considered experimental or unstable,
# https://docs.astral.sh/ruff/preview/
preview = true

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
